// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientConfig.proto

package cn.promptness.rpt.base.config;

public final class ClientConfigProto {
  private ClientConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.promptness.rpt.base.config.ClientConfig.ClientConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serverIp = 1;</code>
     * @return The serverIp.
     */
    String getServerIp();
    /**
     * <code>string serverIp = 1;</code>
     * @return The bytes for serverIp.
     */
    com.google.protobuf.ByteString
        getServerIpBytes();

    /**
     * <code>int32 serverPort = 2;</code>
     * @return The serverPort.
     */
    int getServerPort();

    /**
     * <code>string clientKey = 3;</code>
     * @return The clientKey.
     */
    String getClientKey();
    /**
     * <code>string clientKey = 3;</code>
     * @return The bytes for clientKey.
     */
    com.google.protobuf.ByteString
        getClientKeyBytes();

    /**
     * <code>bool connection = 4;</code>
     * @return The connection.
     */
    boolean getConnection();

    /**
     * <code>string channelId = 5;</code>
     * @return The channelId.
     */
    String getChannelId();
    /**
     * <code>string channelId = 5;</code>
     * @return The bytes for channelId.
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    java.util.List<ClientConfig.RemoteConfig>
        getConfigList();
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    ClientConfig.RemoteConfig getConfig(int index);
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    int getConfigCount();
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    java.util.List<? extends ClientConfig.RemoteConfigOrBuilder>
        getConfigOrBuilderList();
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    ClientConfig.RemoteConfigOrBuilder getConfigOrBuilder(
        int index);

    /**
     * <code>repeated string remoteResult = 7;</code>
     * @return A list containing the remoteResult.
     */
    java.util.List<String>
        getRemoteResultList();
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @return The count of remoteResult.
     */
    int getRemoteResultCount();
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @param index The index of the element to return.
     * @return The remoteResult at the given index.
     */
    String getRemoteResult(int index);
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the remoteResult at the given index.
     */
    com.google.protobuf.ByteString
        getRemoteResultBytes(int index);
  }
  /**
   * Protobuf type {@code cn.promptness.rpt.base.config.ClientConfig.ClientConfig}
   */
  public static final class ClientConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.promptness.rpt.base.config.ClientConfig.ClientConfig)
      ClientConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientConfig.newBuilder() to construct.
    private ClientConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientConfig() {
      serverIp_ = "";
      clientKey_ = "";
      channelId_ = "";
      config_ = java.util.Collections.emptyList();
      remoteResult_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientConfig();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              serverIp_ = s;
              break;
            }
            case 16: {

              serverPort_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              clientKey_ = s;
              break;
            }
            case 32: {

              connection_ = input.readBool();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                config_ = new java.util.ArrayList<RemoteConfig>();
                mutable_bitField0_ |= 0x00000001;
              }
              config_.add(
                  input.readMessage(RemoteConfig.parser(), extensionRegistry));
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                remoteResult_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              remoteResult_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          config_ = java.util.Collections.unmodifiableList(config_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          remoteResult_ = remoteResult_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientConfig.class, Builder.class);
    }

    /**
     * Protobuf enum {@code cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType}
     */
    public enum ProxyType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TCP = 0;</code>
       */
      TCP(0),
      /**
       * <code>HTTP = 1;</code>
       */
      HTTP(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TCP = 0;</code>
       */
      public static final int TCP_VALUE = 0;
      /**
       * <code>HTTP = 1;</code>
       */
      public static final int HTTP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ProxyType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ProxyType forNumber(int value) {
        switch (value) {
          case 0: return TCP;
          case 1: return HTTP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProxyType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ProxyType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProxyType>() {
              public ProxyType findValueByNumber(int number) {
                return ProxyType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientConfig.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProxyType[] VALUES = values();

      public static ProxyType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ProxyType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType)
    }

    public interface RemoteConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 remotePort = 1;</code>
       * @return The remotePort.
       */
      int getRemotePort();

      /**
       * <code>int32 localPort = 2;</code>
       * @return The localPort.
       */
      int getLocalPort();

      /**
       * <code>string localIp = 3;</code>
       * @return The localIp.
       */
      String getLocalIp();
      /**
       * <code>string localIp = 3;</code>
       * @return The bytes for localIp.
       */
      com.google.protobuf.ByteString
          getLocalIpBytes();

      /**
       * <code>string description = 4;</code>
       * @return The description.
       */
      String getDescription();
      /**
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();

      /**
       * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
       * @return The enum numeric value on the wire for proxyType.
       */
      int getProxyTypeValue();
      /**
       * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
       * @return The proxyType.
       */
      ProxyType getProxyType();

      /**
       * <code>string domain = 6;</code>
       * @return The domain.
       */
      String getDomain();
      /**
       * <code>string domain = 6;</code>
       * @return The bytes for domain.
       */
      com.google.protobuf.ByteString
          getDomainBytes();
    }
    /**
     * Protobuf type {@code cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig}
     */
    public static final class RemoteConfig extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig)
        RemoteConfigOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RemoteConfig.newBuilder() to construct.
      private RemoteConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RemoteConfig() {
        localIp_ = "";
        description_ = "";
        proxyType_ = 0;
        domain_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new RemoteConfig();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private RemoteConfig(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                remotePort_ = input.readInt32();
                break;
              }
              case 16: {

                localPort_ = input.readInt32();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                localIp_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                description_ = s;
                break;
              }
              case 40: {
                int rawValue = input.readEnum();

                proxyType_ = rawValue;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                domain_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RemoteConfig.class, Builder.class);
      }

      public static final int REMOTEPORT_FIELD_NUMBER = 1;
      private int remotePort_;
      /**
       * <code>int32 remotePort = 1;</code>
       * @return The remotePort.
       */
      @Override
      public int getRemotePort() {
        return remotePort_;
      }

      public static final int LOCALPORT_FIELD_NUMBER = 2;
      private int localPort_;
      /**
       * <code>int32 localPort = 2;</code>
       * @return The localPort.
       */
      @Override
      public int getLocalPort() {
        return localPort_;
      }

      public static final int LOCALIP_FIELD_NUMBER = 3;
      private volatile Object localIp_;
      /**
       * <code>string localIp = 3;</code>
       * @return The localIp.
       */
      @Override
      public String getLocalIp() {
        Object ref = localIp_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          localIp_ = s;
          return s;
        }
      }
      /**
       * <code>string localIp = 3;</code>
       * @return The bytes for localIp.
       */
      @Override
      public com.google.protobuf.ByteString
          getLocalIpBytes() {
        Object ref = localIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          localIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DESCRIPTION_FIELD_NUMBER = 4;
      private volatile Object description_;
      /**
       * <code>string description = 4;</code>
       * @return The description.
       */
      @Override
      public String getDescription() {
        Object ref = description_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        }
      }
      /**
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      @Override
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PROXYTYPE_FIELD_NUMBER = 5;
      private int proxyType_;
      /**
       * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
       * @return The enum numeric value on the wire for proxyType.
       */
      @Override public int getProxyTypeValue() {
        return proxyType_;
      }
      /**
       * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
       * @return The proxyType.
       */
      @Override public ProxyType getProxyType() {
        @SuppressWarnings("deprecation")
        ProxyType result = ProxyType.valueOf(proxyType_);
        return result == null ? ProxyType.UNRECOGNIZED : result;
      }

      public static final int DOMAIN_FIELD_NUMBER = 6;
      private volatile Object domain_;
      /**
       * <code>string domain = 6;</code>
       * @return The domain.
       */
      @Override
      public String getDomain() {
        Object ref = domain_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        }
      }
      /**
       * <code>string domain = 6;</code>
       * @return The bytes for domain.
       */
      @Override
      public com.google.protobuf.ByteString
          getDomainBytes() {
        Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (remotePort_ != 0) {
          output.writeInt32(1, remotePort_);
        }
        if (localPort_ != 0) {
          output.writeInt32(2, localPort_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localIp_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, localIp_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
        }
        if (proxyType_ != ProxyType.TCP.getNumber()) {
          output.writeEnum(5, proxyType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 6, domain_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (remotePort_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, remotePort_);
        }
        if (localPort_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, localPort_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localIp_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, localIp_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
        }
        if (proxyType_ != ProxyType.TCP.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(5, proxyType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domain_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, domain_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof RemoteConfig)) {
          return super.equals(obj);
        }
        RemoteConfig other = (RemoteConfig) obj;

        if (getRemotePort()
            != other.getRemotePort()) return false;
        if (getLocalPort()
            != other.getLocalPort()) return false;
        if (!getLocalIp()
            .equals(other.getLocalIp())) return false;
        if (!getDescription()
            .equals(other.getDescription())) return false;
        if (proxyType_ != other.proxyType_) return false;
        if (!getDomain()
            .equals(other.getDomain())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + REMOTEPORT_FIELD_NUMBER;
        hash = (53 * hash) + getRemotePort();
        hash = (37 * hash) + LOCALPORT_FIELD_NUMBER;
        hash = (53 * hash) + getLocalPort();
        hash = (37 * hash) + LOCALIP_FIELD_NUMBER;
        hash = (53 * hash) + getLocalIp().hashCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        hash = (37 * hash) + PROXYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + proxyType_;
        hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getDomain().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static RemoteConfig parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RemoteConfig parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RemoteConfig parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RemoteConfig parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RemoteConfig parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RemoteConfig parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RemoteConfig parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static RemoteConfig parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static RemoteConfig parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static RemoteConfig parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static RemoteConfig parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static RemoteConfig parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(RemoteConfig prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig)
          RemoteConfigOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  RemoteConfig.class, Builder.class);
        }

        // Construct using cn.promptness.rpt.base.config.ClientConfigProto.ClientConfig.RemoteConfig.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          remotePort_ = 0;

          localPort_ = 0;

          localIp_ = "";

          description_ = "";

          proxyType_ = 0;

          domain_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_descriptor;
        }

        @Override
        public RemoteConfig getDefaultInstanceForType() {
          return RemoteConfig.getDefaultInstance();
        }

        @Override
        public RemoteConfig build() {
          RemoteConfig result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public RemoteConfig buildPartial() {
          RemoteConfig result = new RemoteConfig(this);
          result.remotePort_ = remotePort_;
          result.localPort_ = localPort_;
          result.localIp_ = localIp_;
          result.description_ = description_;
          result.proxyType_ = proxyType_;
          result.domain_ = domain_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof RemoteConfig) {
            return mergeFrom((RemoteConfig)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(RemoteConfig other) {
          if (other == RemoteConfig.getDefaultInstance()) return this;
          if (other.getRemotePort() != 0) {
            setRemotePort(other.getRemotePort());
          }
          if (other.getLocalPort() != 0) {
            setLocalPort(other.getLocalPort());
          }
          if (!other.getLocalIp().isEmpty()) {
            localIp_ = other.localIp_;
            onChanged();
          }
          if (!other.getDescription().isEmpty()) {
            description_ = other.description_;
            onChanged();
          }
          if (other.proxyType_ != 0) {
            setProxyTypeValue(other.getProxyTypeValue());
          }
          if (!other.getDomain().isEmpty()) {
            domain_ = other.domain_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          RemoteConfig parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (RemoteConfig) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int remotePort_ ;
        /**
         * <code>int32 remotePort = 1;</code>
         * @return The remotePort.
         */
        @Override
        public int getRemotePort() {
          return remotePort_;
        }
        /**
         * <code>int32 remotePort = 1;</code>
         * @param value The remotePort to set.
         * @return This builder for chaining.
         */
        public Builder setRemotePort(int value) {
          
          remotePort_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 remotePort = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearRemotePort() {
          
          remotePort_ = 0;
          onChanged();
          return this;
        }

        private int localPort_ ;
        /**
         * <code>int32 localPort = 2;</code>
         * @return The localPort.
         */
        @Override
        public int getLocalPort() {
          return localPort_;
        }
        /**
         * <code>int32 localPort = 2;</code>
         * @param value The localPort to set.
         * @return This builder for chaining.
         */
        public Builder setLocalPort(int value) {
          
          localPort_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 localPort = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLocalPort() {
          
          localPort_ = 0;
          onChanged();
          return this;
        }

        private Object localIp_ = "";
        /**
         * <code>string localIp = 3;</code>
         * @return The localIp.
         */
        public String getLocalIp() {
          Object ref = localIp_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            localIp_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string localIp = 3;</code>
         * @return The bytes for localIp.
         */
        public com.google.protobuf.ByteString
            getLocalIpBytes() {
          Object ref = localIp_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            localIp_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string localIp = 3;</code>
         * @param value The localIp to set.
         * @return This builder for chaining.
         */
        public Builder setLocalIp(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          localIp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string localIp = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearLocalIp() {
          
          localIp_ = getDefaultInstance().getLocalIp();
          onChanged();
          return this;
        }
        /**
         * <code>string localIp = 3;</code>
         * @param value The bytes for localIp to set.
         * @return This builder for chaining.
         */
        public Builder setLocalIpBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          localIp_ = value;
          onChanged();
          return this;
        }

        private Object description_ = "";
        /**
         * <code>string description = 4;</code>
         * @return The description.
         */
        public String getDescription() {
          Object ref = description_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string description = 4;</code>
         * @return The bytes for description.
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string description = 4;</code>
         * @param value The description to set.
         * @return This builder for chaining.
         */
        public Builder setDescription(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string description = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearDescription() {
          
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <code>string description = 4;</code>
         * @param value The bytes for description to set.
         * @return This builder for chaining.
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          description_ = value;
          onChanged();
          return this;
        }

        private int proxyType_ = 0;
        /**
         * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
         * @return The enum numeric value on the wire for proxyType.
         */
        @Override public int getProxyTypeValue() {
          return proxyType_;
        }
        /**
         * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
         * @param value The enum numeric value on the wire for proxyType to set.
         * @return This builder for chaining.
         */
        public Builder setProxyTypeValue(int value) {
          
          proxyType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
         * @return The proxyType.
         */
        @Override
        public ProxyType getProxyType() {
          @SuppressWarnings("deprecation")
          ProxyType result = ProxyType.valueOf(proxyType_);
          return result == null ? ProxyType.UNRECOGNIZED : result;
        }
        /**
         * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
         * @param value The proxyType to set.
         * @return This builder for chaining.
         */
        public Builder setProxyType(ProxyType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          proxyType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.cn.promptness.rpt.base.config.ClientConfig.ClientConfig.ProxyType proxyType = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearProxyType() {
          
          proxyType_ = 0;
          onChanged();
          return this;
        }

        private Object domain_ = "";
        /**
         * <code>string domain = 6;</code>
         * @return The domain.
         */
        public String getDomain() {
          Object ref = domain_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            domain_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string domain = 6;</code>
         * @return The bytes for domain.
         */
        public com.google.protobuf.ByteString
            getDomainBytes() {
          Object ref = domain_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            domain_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string domain = 6;</code>
         * @param value The domain to set.
         * @return This builder for chaining.
         */
        public Builder setDomain(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          domain_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string domain = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearDomain() {
          
          domain_ = getDefaultInstance().getDomain();
          onChanged();
          return this;
        }
        /**
         * <code>string domain = 6;</code>
         * @param value The bytes for domain to set.
         * @return This builder for chaining.
         */
        public Builder setDomainBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          domain_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig)
      }

      // @@protoc_insertion_point(class_scope:cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig)
      private static final RemoteConfig DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new RemoteConfig();
      }

      public static RemoteConfig getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RemoteConfig>
          PARSER = new com.google.protobuf.AbstractParser<RemoteConfig>() {
        @Override
        public RemoteConfig parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RemoteConfig(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RemoteConfig> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<RemoteConfig> getParserForType() {
        return PARSER;
      }

      @Override
      public RemoteConfig getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SERVERIP_FIELD_NUMBER = 1;
    private volatile Object serverIp_;
    /**
     * <code>string serverIp = 1;</code>
     * @return The serverIp.
     */
    @Override
    public String getServerIp() {
      Object ref = serverIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverIp_ = s;
        return s;
      }
    }
    /**
     * <code>string serverIp = 1;</code>
     * @return The bytes for serverIp.
     */
    @Override
    public com.google.protobuf.ByteString
        getServerIpBytes() {
      Object ref = serverIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERPORT_FIELD_NUMBER = 2;
    private int serverPort_;
    /**
     * <code>int32 serverPort = 2;</code>
     * @return The serverPort.
     */
    @Override
    public int getServerPort() {
      return serverPort_;
    }

    public static final int CLIENTKEY_FIELD_NUMBER = 3;
    private volatile Object clientKey_;
    /**
     * <code>string clientKey = 3;</code>
     * @return The clientKey.
     */
    @Override
    public String getClientKey() {
      Object ref = clientKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientKey_ = s;
        return s;
      }
    }
    /**
     * <code>string clientKey = 3;</code>
     * @return The bytes for clientKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getClientKeyBytes() {
      Object ref = clientKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONNECTION_FIELD_NUMBER = 4;
    private boolean connection_;
    /**
     * <code>bool connection = 4;</code>
     * @return The connection.
     */
    @Override
    public boolean getConnection() {
      return connection_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 5;
    private volatile Object channelId_;
    /**
     * <code>string channelId = 5;</code>
     * @return The channelId.
     */
    @Override
    public String getChannelId() {
      Object ref = channelId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>string channelId = 5;</code>
     * @return The bytes for channelId.
     */
    @Override
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIG_FIELD_NUMBER = 6;
    private java.util.List<RemoteConfig> config_;
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    @Override
    public java.util.List<RemoteConfig> getConfigList() {
      return config_;
    }
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    @Override
    public java.util.List<? extends RemoteConfigOrBuilder>
        getConfigOrBuilderList() {
      return config_;
    }
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    @Override
    public int getConfigCount() {
      return config_.size();
    }
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    @Override
    public RemoteConfig getConfig(int index) {
      return config_.get(index);
    }
    /**
     * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
     */
    @Override
    public RemoteConfigOrBuilder getConfigOrBuilder(
        int index) {
      return config_.get(index);
    }

    public static final int REMOTERESULT_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList remoteResult_;
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @return A list containing the remoteResult.
     */
    public com.google.protobuf.ProtocolStringList
        getRemoteResultList() {
      return remoteResult_;
    }
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @return The count of remoteResult.
     */
    public int getRemoteResultCount() {
      return remoteResult_.size();
    }
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @param index The index of the element to return.
     * @return The remoteResult at the given index.
     */
    public String getRemoteResult(int index) {
      return remoteResult_.get(index);
    }
    /**
     * <code>repeated string remoteResult = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the remoteResult at the given index.
     */
    public com.google.protobuf.ByteString
        getRemoteResultBytes(int index) {
      return remoteResult_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverIp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverIp_);
      }
      if (serverPort_ != 0) {
        output.writeInt32(2, serverPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientKey_);
      }
      if (connection_ != false) {
        output.writeBool(4, connection_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channelId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, channelId_);
      }
      for (int i = 0; i < config_.size(); i++) {
        output.writeMessage(6, config_.get(i));
      }
      for (int i = 0; i < remoteResult_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, remoteResult_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverIp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverIp_);
      }
      if (serverPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientKey_);
      }
      if (connection_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, connection_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channelId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, channelId_);
      }
      for (int i = 0; i < config_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, config_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < remoteResult_.size(); i++) {
          dataSize += computeStringSizeNoTag(remoteResult_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRemoteResultList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientConfig)) {
        return super.equals(obj);
      }
      ClientConfig other = (ClientConfig) obj;

      if (!getServerIp()
          .equals(other.getServerIp())) return false;
      if (getServerPort()
          != other.getServerPort()) return false;
      if (!getClientKey()
          .equals(other.getClientKey())) return false;
      if (getConnection()
          != other.getConnection()) return false;
      if (!getChannelId()
          .equals(other.getChannelId())) return false;
      if (!getConfigList()
          .equals(other.getConfigList())) return false;
      if (!getRemoteResultList()
          .equals(other.getRemoteResultList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERIP_FIELD_NUMBER;
      hash = (53 * hash) + getServerIp().hashCode();
      hash = (37 * hash) + SERVERPORT_FIELD_NUMBER;
      hash = (53 * hash) + getServerPort();
      hash = (37 * hash) + CLIENTKEY_FIELD_NUMBER;
      hash = (53 * hash) + getClientKey().hashCode();
      hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConnection());
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      if (getConfigCount() > 0) {
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfigList().hashCode();
      }
      if (getRemoteResultCount() > 0) {
        hash = (37 * hash) + REMOTERESULT_FIELD_NUMBER;
        hash = (53 * hash) + getRemoteResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.promptness.rpt.base.config.ClientConfig.ClientConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.promptness.rpt.base.config.ClientConfig.ClientConfig)
        ClientConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientConfig.class, Builder.class);
      }

      // Construct using cn.promptness.rpt.base.config.ClientConfigProto.ClientConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConfigFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        serverIp_ = "";

        serverPort_ = 0;

        clientKey_ = "";

        connection_ = false;

        channelId_ = "";

        if (configBuilder_ == null) {
          config_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          configBuilder_.clear();
        }
        remoteResult_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientConfigProto.internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor;
      }

      @Override
      public ClientConfig getDefaultInstanceForType() {
        return ClientConfig.getDefaultInstance();
      }

      @Override
      public ClientConfig build() {
        ClientConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientConfig buildPartial() {
        ClientConfig result = new ClientConfig(this);
        int from_bitField0_ = bitField0_;
        result.serverIp_ = serverIp_;
        result.serverPort_ = serverPort_;
        result.clientKey_ = clientKey_;
        result.connection_ = connection_;
        result.channelId_ = channelId_;
        if (configBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            config_ = java.util.Collections.unmodifiableList(config_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.config_ = config_;
        } else {
          result.config_ = configBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          remoteResult_ = remoteResult_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.remoteResult_ = remoteResult_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientConfig) {
          return mergeFrom((ClientConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientConfig other) {
        if (other == ClientConfig.getDefaultInstance()) return this;
        if (!other.getServerIp().isEmpty()) {
          serverIp_ = other.serverIp_;
          onChanged();
        }
        if (other.getServerPort() != 0) {
          setServerPort(other.getServerPort());
        }
        if (!other.getClientKey().isEmpty()) {
          clientKey_ = other.clientKey_;
          onChanged();
        }
        if (other.getConnection() != false) {
          setConnection(other.getConnection());
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (configBuilder_ == null) {
          if (!other.config_.isEmpty()) {
            if (config_.isEmpty()) {
              config_ = other.config_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConfigIsMutable();
              config_.addAll(other.config_);
            }
            onChanged();
          }
        } else {
          if (!other.config_.isEmpty()) {
            if (configBuilder_.isEmpty()) {
              configBuilder_.dispose();
              configBuilder_ = null;
              config_ = other.config_;
              bitField0_ = (bitField0_ & ~0x00000001);
              configBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConfigFieldBuilder() : null;
            } else {
              configBuilder_.addAllMessages(other.config_);
            }
          }
        }
        if (!other.remoteResult_.isEmpty()) {
          if (remoteResult_.isEmpty()) {
            remoteResult_ = other.remoteResult_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRemoteResultIsMutable();
            remoteResult_.addAll(other.remoteResult_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object serverIp_ = "";
      /**
       * <code>string serverIp = 1;</code>
       * @return The serverIp.
       */
      public String getServerIp() {
        Object ref = serverIp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverIp = 1;</code>
       * @return The bytes for serverIp.
       */
      public com.google.protobuf.ByteString
          getServerIpBytes() {
        Object ref = serverIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverIp = 1;</code>
       * @param value The serverIp to set.
       * @return This builder for chaining.
       */
      public Builder setServerIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverIp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerIp() {
        
        serverIp_ = getDefaultInstance().getServerIp();
        onChanged();
        return this;
      }
      /**
       * <code>string serverIp = 1;</code>
       * @param value The bytes for serverIp to set.
       * @return This builder for chaining.
       */
      public Builder setServerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverIp_ = value;
        onChanged();
        return this;
      }

      private int serverPort_ ;
      /**
       * <code>int32 serverPort = 2;</code>
       * @return The serverPort.
       */
      @Override
      public int getServerPort() {
        return serverPort_;
      }
      /**
       * <code>int32 serverPort = 2;</code>
       * @param value The serverPort to set.
       * @return This builder for chaining.
       */
      public Builder setServerPort(int value) {
        
        serverPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverPort = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerPort() {
        
        serverPort_ = 0;
        onChanged();
        return this;
      }

      private Object clientKey_ = "";
      /**
       * <code>string clientKey = 3;</code>
       * @return The clientKey.
       */
      public String getClientKey() {
        Object ref = clientKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientKey = 3;</code>
       * @return The bytes for clientKey.
       */
      public com.google.protobuf.ByteString
          getClientKeyBytes() {
        Object ref = clientKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientKey = 3;</code>
       * @param value The clientKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientKey = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientKey() {
        
        clientKey_ = getDefaultInstance().getClientKey();
        onChanged();
        return this;
      }
      /**
       * <code>string clientKey = 3;</code>
       * @param value The bytes for clientKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientKey_ = value;
        onChanged();
        return this;
      }

      private boolean connection_ ;
      /**
       * <code>bool connection = 4;</code>
       * @return The connection.
       */
      @Override
      public boolean getConnection() {
        return connection_;
      }
      /**
       * <code>bool connection = 4;</code>
       * @param value The connection to set.
       * @return This builder for chaining.
       */
      public Builder setConnection(boolean value) {
        
        connection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool connection = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnection() {
        
        connection_ = false;
        onChanged();
        return this;
      }

      private Object channelId_ = "";
      /**
       * <code>string channelId = 5;</code>
       * @return The channelId.
       */
      public String getChannelId() {
        Object ref = channelId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string channelId = 5;</code>
       * @return The bytes for channelId.
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channelId = 5;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 5;</code>
       * @param value The bytes for channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<RemoteConfig> config_ =
        java.util.Collections.emptyList();
      private void ensureConfigIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          config_ = new java.util.ArrayList<RemoteConfig>(config_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          RemoteConfig, RemoteConfig.Builder, RemoteConfigOrBuilder> configBuilder_;

      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public java.util.List<RemoteConfig> getConfigList() {
        if (configBuilder_ == null) {
          return java.util.Collections.unmodifiableList(config_);
        } else {
          return configBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public int getConfigCount() {
        if (configBuilder_ == null) {
          return config_.size();
        } else {
          return configBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public RemoteConfig getConfig(int index) {
        if (configBuilder_ == null) {
          return config_.get(index);
        } else {
          return configBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder setConfig(
          int index, RemoteConfig value) {
        if (configBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigIsMutable();
          config_.set(index, value);
          onChanged();
        } else {
          configBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder setConfig(
          int index, RemoteConfig.Builder builderForValue) {
        if (configBuilder_ == null) {
          ensureConfigIsMutable();
          config_.set(index, builderForValue.build());
          onChanged();
        } else {
          configBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder addConfig(RemoteConfig value) {
        if (configBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigIsMutable();
          config_.add(value);
          onChanged();
        } else {
          configBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder addConfig(
          int index, RemoteConfig value) {
        if (configBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConfigIsMutable();
          config_.add(index, value);
          onChanged();
        } else {
          configBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder addConfig(
          RemoteConfig.Builder builderForValue) {
        if (configBuilder_ == null) {
          ensureConfigIsMutable();
          config_.add(builderForValue.build());
          onChanged();
        } else {
          configBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder addConfig(
          int index, RemoteConfig.Builder builderForValue) {
        if (configBuilder_ == null) {
          ensureConfigIsMutable();
          config_.add(index, builderForValue.build());
          onChanged();
        } else {
          configBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder addAllConfig(
          Iterable<? extends RemoteConfig> values) {
        if (configBuilder_ == null) {
          ensureConfigIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, config_);
          onChanged();
        } else {
          configBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder clearConfig() {
        if (configBuilder_ == null) {
          config_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          configBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public Builder removeConfig(int index) {
        if (configBuilder_ == null) {
          ensureConfigIsMutable();
          config_.remove(index);
          onChanged();
        } else {
          configBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public RemoteConfig.Builder getConfigBuilder(
          int index) {
        return getConfigFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public RemoteConfigOrBuilder getConfigOrBuilder(
          int index) {
        if (configBuilder_ == null) {
          return config_.get(index);  } else {
          return configBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public java.util.List<? extends RemoteConfigOrBuilder>
           getConfigOrBuilderList() {
        if (configBuilder_ != null) {
          return configBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(config_);
        }
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public RemoteConfig.Builder addConfigBuilder() {
        return getConfigFieldBuilder().addBuilder(
            RemoteConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public RemoteConfig.Builder addConfigBuilder(
          int index) {
        return getConfigFieldBuilder().addBuilder(
            index, RemoteConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.promptness.rpt.base.config.ClientConfig.ClientConfig.RemoteConfig config = 6;</code>
       */
      public java.util.List<RemoteConfig.Builder>
           getConfigBuilderList() {
        return getConfigFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          RemoteConfig, RemoteConfig.Builder, RemoteConfigOrBuilder>
          getConfigFieldBuilder() {
        if (configBuilder_ == null) {
          configBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              RemoteConfig, RemoteConfig.Builder, RemoteConfigOrBuilder>(
                  config_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          config_ = null;
        }
        return configBuilder_;
      }

      private com.google.protobuf.LazyStringList remoteResult_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRemoteResultIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          remoteResult_ = new com.google.protobuf.LazyStringArrayList(remoteResult_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @return A list containing the remoteResult.
       */
      public com.google.protobuf.ProtocolStringList
          getRemoteResultList() {
        return remoteResult_.getUnmodifiableView();
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @return The count of remoteResult.
       */
      public int getRemoteResultCount() {
        return remoteResult_.size();
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @param index The index of the element to return.
       * @return The remoteResult at the given index.
       */
      public String getRemoteResult(int index) {
        return remoteResult_.get(index);
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the remoteResult at the given index.
       */
      public com.google.protobuf.ByteString
          getRemoteResultBytes(int index) {
        return remoteResult_.getByteString(index);
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @param index The index to set the value at.
       * @param value The remoteResult to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteResult(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRemoteResultIsMutable();
        remoteResult_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @param value The remoteResult to add.
       * @return This builder for chaining.
       */
      public Builder addRemoteResult(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRemoteResultIsMutable();
        remoteResult_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @param values The remoteResult to add.
       * @return This builder for chaining.
       */
      public Builder addAllRemoteResult(
          Iterable<String> values) {
        ensureRemoteResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, remoteResult_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemoteResult() {
        remoteResult_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string remoteResult = 7;</code>
       * @param value The bytes of the remoteResult to add.
       * @return This builder for chaining.
       */
      public Builder addRemoteResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRemoteResultIsMutable();
        remoteResult_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.promptness.rpt.base.config.ClientConfig.ClientConfig)
    }

    // @@protoc_insertion_point(class_scope:cn.promptness.rpt.base.config.ClientConfig.ClientConfig)
    private static final ClientConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientConfig();
    }

    public static ClientConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientConfig>
        PARSER = new com.google.protobuf.AbstractParser<ClientConfig>() {
      @Override
      public ClientConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientConfig> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientConfig> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ClientConfig.proto\022*cn.promptness.rpt." +
      "base.config.ClientConfig\"\300\003\n\014ClientConfi" +
      "g\022\020\n\010serverIp\030\001 \001(\t\022\022\n\nserverPort\030\002 \001(\005\022" +
      "\021\n\tclientKey\030\003 \001(\t\022\022\n\nconnection\030\004 \001(\010\022\021" +
      "\n\tchannelId\030\005 \001(\t\022U\n\006config\030\006 \003(\0132E.cn.p" +
      "romptness.rpt.base.config.ClientConfig.C" +
      "lientConfig.RemoteConfig\022\024\n\014remoteResult" +
      "\030\007 \003(\t\032\302\001\n\014RemoteConfig\022\022\n\nremotePort\030\001 " +
      "\001(\005\022\021\n\tlocalPort\030\002 \001(\005\022\017\n\007localIp\030\003 \001(\t\022" +
      "\023\n\013description\030\004 \001(\t\022U\n\tproxyType\030\005 \001(\0162" +
      "B.cn.promptness.rpt.base.config.ClientCo" +
      "nfig.ClientConfig.ProxyType\022\016\n\006domain\030\006 " +
      "\001(\t\"\036\n\tProxyType\022\007\n\003TCP\020\000\022\010\n\004HTTP\020\001B4\n\035c" +
      "n.promptness.rpt.base.configB\021ClientConf" +
      "igProtoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor,
        new String[] { "ServerIp", "ServerPort", "ClientKey", "Connection", "ChannelId", "Config", "RemoteResult", });
    internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_descriptor =
      internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_descriptor.getNestedTypes().get(0);
    internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_promptness_rpt_base_config_ClientConfig_ClientConfig_RemoteConfig_descriptor,
        new String[] { "RemotePort", "LocalPort", "LocalIp", "Description", "ProxyType", "Domain", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
